print("Let's play Mad Libs for Homework 1\nType one word responses to the following:\n")
name = input("proper_name ==> ")
print(name)
adjective = input("adjective ==> ")
print(adjective)
noun = input("noun ==> ")
print(noun)
verb = input("verb ==> ")
print(verb)
verb2 = input("verb ==> ")
print(verb2)
noun2 = input("noun ==> ")
print(noun2)
emotion = input("emotion ==> ")
print(emotion)
verb3 = input("verb ==> ")
print(verb3)
noun3 = input("noun ==> ")
print(noun3)
season = input("season ==> ")
print(season)
adjective2 = input("adjective ==> ")
print(adjective2)
emotion2 = input("emotion ==> ")
print(emotion2)
teamname = input("team-name ==> ")
print(teamname)
noun4 = input("noun ==> ")
print(noun4)
adjective3 = input("adjective ==> ")
print(adjective3)
print("\nHere is your Mad Lib...\n")

print("Good morning " + name + "!\n")
print("This will be a/an " + adjective + " " + noun + "! Are you " + verb + " forward to it?")
print("You will " + verb2 + " a lot of " + noun2 + " and feel " + emotion + " when you do.")
print("If you do not, you will " + verb3 + " this " + noun3 + ".\n")
print("This " + season + " was " + adjective2 + ". Were you " + emotion2 + " when " + teamname + " won\nthe " + noun4 + "?\n")
print("Have a/an " + adjective3 + " day!")